export const FEATURES = {
  DAILY_BOOK:                     'daily_book',
  PDF_IMPORT:                     'pdf_import',
  STATUS_TRACKING:                'status_tracking',
  AUDIT_TRAIL:                    'audit_trail',
  MULTI_USER_ACCESS:              'multi_user_access',
  EXPORT_PRINT:                   'export_print',
  CALENDAR_VIEW:                  'calendar_view',
  PROF_EMAIL_DIRECT:              'prof_email_direct',
  ANALYTICS_DASHBOARD:            'analytics_dashboard',
  COURSE_DOSSIER:                 'course_dossier',
  LIVE_STATUS_BOARD:              'live_status_board',
  STUDENT_ACCOMMODATION_PROFILES: 'student_accommodation_profiles',
  SMART_EXAM_NOTIFICATIONS:       'smart_exam_notifications',
  CUSTOM_FORM_FIELDS:             'custom_form_fields',
  CUSTOM_SCHEMA_EXTENSIONS:       'custom_schema_extensions',
  SSO_SAML:                       'sso_saml',
  DATA_RESIDENCY_SLA:             'data_residency_sla',
};
